resources:
  - name: windows-stemcell-pipeline
    type: git
    source:
      uri: https://github.com/cdelashmutt-pivotal/windows-stemcell-pipeline
      branch: master
  - name: base-vm
    type: s3
    source:
      bucket: vmx-with-windows-update
      regexp: windows-stem-(.*).ova
      access_key_id: ((s3_access_key))
      secret_access_key: ((s3_secret_key))
      endpoint: ((s3_endpoint_uri))
  - name: stemcell
    type: s3
    source:
      bucket: stemcells
      access_key_id: ((s3_access_key))
      secret_access_key: ((s3_secret_key))
      endpoint: ((s3_endpoint_uri))

jobs:
  - name: import-vm
    plan:
      - get: windows-stemcell-pipeline
      - get: base-vm
      - task: import-vm
        file: windows-stemcell-pipeline/import-vm/import-vm.yml
        params:
          VCENTER_HOST: ((vcenter_host))
          VCENTER_USER: ((vcenter_user))
          VCENTER_PASSWORD: ((vcenter_password))
  - name: export-vm
    plan:
      - put: stemcell
      - task: export-vm
        file: windows-stemcell-pipeline/export-vm/export-vm.yml
        params:
          VCENTER_HOST: ((vcenter_host))
          VCENTER_USER: ((vcenter_user))
          VCENTER_PASSWORD: ((vcenter_password))
        
